### ISSUE TITLE
GError: Reached stack-limit of 50

### ISSUE THREAD

**Issue by pabluk** [pabluk/NotifyAll#5]
```
Exception in thread libnotifyall.services.TwitterService:`
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 525, in __bootstrap_inner
    self.run()
  File "/home/jpablo/Dev/Projects/NotifyAll/libnotifyall/Service.py", line 82, in run
    self.show_messages()
  File "/home/jpablo/Dev/Projects/NotifyAll/libnotifyall/Service.py", line 64, in show_messages
    msg.show()
  File "/home/jpablo/Dev/Projects/NotifyAll/libnotifyall/Message.py", line 42, in show
    m.show()
GError: Reached stack-limit of 50
```

**Comment by pabluk** [comment]
Apparently there is a limitation of libnotify.
